[server]
port = 8081

[tickets]

    # no more than 1 ticket every 30 seconds can be created
    global_delay = 30

    [tickets.clean]
    auto_clean = true
    task_delay = 1 # every minute
    configuration = 1 # a hour
    reception = 720 # a month
    received = 24 # a day
    sending = 48 # two days
    sent = 24 # a day
    dispute = 8760 # a year

[bitcoin]
test_net = false
rate = 0.99 # what we send back (fee = 1-rate)
master_address = "bc1qm9g2k3fznl2a9vghnpnwem87p03txl4y5lahyu"
required_confirmations = 1

# minimal required amount = static + fee * relative
static_minimal_amount = 0.0005
relative_minimal_amount = 2