[server]
port = 8080

[tickets]

    # no more than 1 ticket every 30 seconds can be created
    global_delay = 30

    [tickets.clean]
    auto_clean = true
    task_delay = 1 # every minute
    configuration = 1 # a hour
    reception = 720 # a month
    received = 24 # a day
    sending = 48 # two days
    sent = 24 # a day
    dispute = 8760 # a year

[bitcoin]
rate = 0.01 # what we take
master_address = "bc1qm9g2k3fznl2a9vghnpnwem87p03txl4y5lahyu"
test_net = true